name: Local Config 
version: 1.0.0
schema: v1
# This config is using LiteLLM router to switch between local & cloud models
# See llm-router/Developer/llm-router configurations
models:
  - name: Hybrid Coder (LiteLLM)
    provider: "openai"
    model: "hybrid-coder"
    apiBase: "http://127.0.0.1:8000/v1"
    apiKey: "not-needed"
    roles:
      - chat
      - edit
      - apply
      - autocomplete